Fix native types tests for CockroachDB
prisma/prisma-engines pull request #2308
Opened 2021-10-12 22:17 UTC by otan

2021-10-12 22:20 UTC, otan commented
cc @Weakky @dpetrick

2021-10-14 10:53 UTC, dpetrick requested changes

2021-10-14 10:53 UTC, dpetrick commented on query-engine/connector-test-kit-rs/query-engine-tests/tests/writes/data_types/native_types/postgres.rs
> +    #[connector_test(schema(schema_decimal), exclude(Cockroach))]
This shouldn't work (see other PR), Cockroach is not a connector but a version.

2021-10-14 10:53 UTC, dpetrick commented
Needed to revise the review because of inconsistencies I found later in other PRs.

2021-10-14 11:19 UTC, merged