Fixed Redirection Links in Error reference page
prisma/prisma-engines pull request #2916
Opened 2022-05-11 11:08 UTC by nurul3101

Fixed Error reference redirection links:

Related PR:

- https://github.com/prisma/docs/pull/3121

Conversation:

- https://github.com/prisma/docs/pull/3121#discussion_r866151735

2022-05-11 11:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prisma/prisma-engines?pullRequest=2916) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prisma/prisma-engines?pullRequest=2916) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prisma/prisma-engines?pullRequest=2916) it.</sub>

2022-05-11 21:03 UTC, janpio requested changes
These links are rendered in the terminal, Markdown does not work there.
Onl the `about` change makes sense here.

2022-05-12 08:45 UTC, nurul3101 commented
Got it, just kept the about change and reverted other changes.

2022-05-12 17:14 UTC, janpio approved these changes

2022-08-18 13:52 UTC, merged