fix: detect findUniqueOrThrow as a compactable findUnique operation
prisma/prisma-engines pull request #4014
Opened 2023-06-01 00:06 UTC by hayes

Currently findUniqueOrThrow callas are not being compacted/optimized like findUnique calls.  As far as I can tell, there is no reason this would be intentional, and many other checks for isFindUnique currently do something equivelent to `name.startsWith('findUnique')`

2023-06-01 00:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prisma/prisma-engines?pullRequest=4014) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prisma/prisma-engines?pullRequest=4014) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prisma/prisma-engines?pullRequest=4014) it.</sub>

2023-06-01 08:35 UTC, SevInf requested changes
Hi @hayes. 
Not compacting `findUniqueOrThrow` at the moment is intentional (#3458, prisma/prisma#16548), as it would involve more work then just batching the queries into single SQL statement.  I believe this PR just brings prisma/prisma#16548 back and does not actually fix the batching, (see `queries::batch::select_one_singular::singular_batch::repro_16548` test).

We will be willing to merge proper fix for `*OrThrow` variant batching, but this PR needs more work at the moment.

2023-06-01 20:46 UTC, hayes commented
@SevInf thanks for taking a look, and sorry for opening the PR without actually getting my tests running locally.

I looked at this a bit more today, and the proper fix doesn't seem overly complicated, but this is my first time looking at prisma-engine, so I may be missing some things.

I've updated the PR with a basic implementation to test that my understanding is correct, but there are a few things I could use some help figuring out:

1. When mapping the findMany back to the findUniqueOrThrow payloads, we need to insert an error response, but I was having a hard time figuring out how to generate the correct error here (lots of wrapping and indirection in the various error types/enums).
  * I didn't try to hard to verify this, but it looks like `findUnique` with `rejectOnUnauthorized` would just return null, and create the error in the client, I assume that for `findUniqueOrThrow` the error message is intended to come from the engine instead of the client?
2.  In `CompactDocument` we need to track if the original queries were using `findUnique` or `findUniqueOrThrow` for 2 reasons: we need to have the single field name to map back to, and we need to know if we should insert an error or just a null result when a result is missing
  * I am currently assuming that findUniqueOrThrow and findUnique are batched separately.  The batch ids generated, I think will be different between these 2 methods, so batching these together would also require client changes
  * tracking this per query rather than per batch would add more complexity, and not sure if this would be worth the added complexity
  * This is currently tracked as a `suffix` string.  This feels a bit hacky, but I have not written a ton of rust, and am not familiar enough with this code base to know the best way to track that state
3. The regression test for the issue you mentioned explicitly check that things shouldn't be batched. I think it should be safe to update the test to allow batching, as long as the response doesn't change (it currently does because the errors are not being generated correctly), but want to confirm my understanding of the issue was correct before changing that

2023-06-01 20:48 UTC, hayes commented on query-engine/connector-test-kit-rs/query-engine-tests/tests/queries/batch/select_one_singular.rs
> +        // insta::assert_snapshot!(
this currently fails because errors are not being formatted correctly

2023-06-01 20:49 UTC, hayes commented on query-engine/request-handlers/src/handler.rs
> +                                    ));
this error seems to be missing a couple layers of wrapping, but I wasn't able to figure out the how to correctly reproduce this error

2023-06-05 14:56 UTC, miguelff commented
Answered your questions and suggested a few changes to your (already promising patch in https://github.com/hayes/prisma-engines/pull/1

2023-06-05 15:51 UTC, miguelff commented
Superseded by https://github.com/prisma/prisma-engines/pull/4019. I'm taking it from there.

2023-06-05 15:51 UTC, closed without merging