feat(driver-adapters): automate npm publish
prisma/prisma-engines pull request #4283
Opened 2023-09-26 11:26 UTC by jkomyno

This PR closes https://github.com/prisma/team-orm/issues/361.

2023-09-26 11:27 UTC, jkomyno commented on .github/workflows/publish-driver-adapters.yml
> +          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DRIVER_ADAPTERS_FAILING }}
TODO: add secret `SLACK_WEBHOOK_DRIVER_ADAPTERS_FAILING`. This should be similar to `SLACK_WEBHOOK_WASM_FAILING`.

2023-09-26 11:50 UTC, jkomyno commented
Note: this PR can be tested locally via:

```sh
act -s GITHUB_TOKEN="$(gh auth token)" -j build -W .github/workflows/publish-driver-adapters.yml --input enginesWrapperVersion="alpha-0.0.1" --input engineHash="61d77d2871e6b839403a101940abdb0e12d8ee1d"
```

2023-09-26 11:51 UTC, jkomyno commented on .github/workflows/publish-driver-adapters.yml
> +      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DRIVER_ADAPTERS_FAILING }}
TODO: add back once the `SLACK_WEBHOOK_DRIVER_ADAPTERS_FAILING` secret is added to the repository.

2023-09-26 11:51 UTC, jkomyno commented on .github/workflows/publish-driver-adapters.yml
> +          publish: pnpm publish --dry-run -r --access public --tag ${{ github.event.inputs.npmDistTag }}
TODO: remove `--dry-run` once we're sure the publish step works fine.

2023-09-26 23:54 UTC, janpio reviewed
Do I understand correctly that this would also publish the driver adapter packages with the same engines-wrapper like version a la `5.4.0-25.53d58ea0a4600a7f95eaeb1bff7b99c7d552671d`?

As these are packages installed by our users directly, vs something included in the CLI and Client or VS Code extension, I don't think that will necessarily work and be a good experience for the, We would also have no differentation between `dev` and real release version.

So if I understood this correctly, our assumptions here were wrong and should probably be revisited.

---

What the sprint document included and meant, was probably "only" to make sure that no one has to run publish to npm manually when we upgrade a driver adapter. The current `0.x` version is probably ok and even better for that until we figure out exactly how to deal with all this.

2023-09-27 12:26 UTC, janpio requested changes
On hold until https://github.com/prisma/team-orm/issues/386

2023-10-06 16:37 UTC, closed without merging