fix: D1 tests
prisma/prisma-engines pull request #4929
Opened 2024-06-19 13:39 UTC by jkomyno

2024-06-19 13:47 UTC, jkomyno commented on query-engine/driver-adapters/src/conversion/sqlite.rs
> +        quaint::ValueType::Int64(Some(value)) => JSArg::SafeInt(*value as i32),
Controversial fix:

2024-06-20 08:21 UTC, SevInf requested changes
I don't think we should merge this.
Yes, it fixes some of the failures, but it also silently [screws up every int that is larger than 32 bits](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9664d971c7d258ebf5894ca618305ac7).
Error is better than silently reading/writing garbage.

2024-06-20 11:22 UTC, jkomyno commented
> I don't think we should merge this. Yes, it fixes some of the failures, but it also silently [screws up every int that is larger than 32 bits](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9664d971c7d258ebf5894ca618305ac7). Error is better than silently reading/writing garbage.

yes, that's indeed not desireable. Would you have any advice to bypass the string serialisation of `i64`?

2024-06-21 16:20 UTC, SevInf commented
Copying what I wrote in Slack in conversation with @jkomyno:

What I am thinking the best course of action here: do this change in D1 adapter code, not in the engines, so we at least won’t affect up Turso.
- for that we need to pass value types to the adapter, probably, another vector, `argTypes` [here[(https://github.com/prisma/prisma-engines/blob/289ad74feeb732dff1b2ecbbf974b9404b87205b/query-engine/driver-adapters/src/queryable.rs#L70) and adding new corresponding enum, derived from `QuaintValue` (type part only.
So, we are keeping i64 serialization as string on the engine side.

Then in the D1 adapter:
- Check argument types before sending them to D1.
- If we see Int64 - cast string to number but ensure it is done safely without data loss.
-  If cast can not be done  (number does not fit into 56bit, above `MAX_SAFE_INTEGER` or below `MIN_SAFE_INTEGER`) - throw an error telling user exactly that.

2024-07-30 13:26 UTC, closed without merging