feat(prisma-fmt): add get_datamodel method
prisma/prisma-engines pull request #4946
Opened 2024-07-09 12:17 UTC by aqrln

Add `get_datamodel` method to get just that part of the DMMF without building, serializing, sending across WASM boundary and then deserializing the whole DMMF.

We will also need information about the indexes (currently only unique indexes are included there) and, later, spans of the entities in the schema file.

2024-07-09 12:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/prisma/prisma-engines?pullRequest=4946) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/prisma/prisma-engines?pullRequest=4946) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/prisma/prisma-engines?pullRequest=4946) it.</sub>

2024-07-09 13:29 UTC, Druue approved these changes

2024-07-09 13:56 UTC, jkomyno requested changes
Is it expected to fail on ecosystem-tests?

https://github.com/prisma/ecosystem-tests/actions/runs/9858314744/job/27219470868#step:8:223

2024-07-09 21:26 UTC, aqrln commented
@jkomyno everything passes on another try (except one job failing due to file name being too long on windows): https://github.com/prisma/ecosystem-tests/actions/runs/9864026111/job/27238821658

2024-07-10 08:07 UTC, jkomyno approved these changes

2024-07-10 09:34 UTC, merged